eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
  

spring:    
  cloud:
    gateway:
      discovery:
         locator:
            enabled: true
      routes:
      - id: Train-Details-Service
        uri: lb://Train-Details-Service
        predicates:
        - Path=/trains/**
      - id: Booking-Order-Service
        uri: lb://Booking-Order-Service
        predicates:
        - Path=/orders/**
      - id: Train-Search-Service
        uri: lb://Train-Search-Service
        predicates:
        - Path=/search/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        
        
     