server:
  port: 8083
spring:
  application:
    name: SPRING-BOOT-PAYTM-PAYMENT
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
